const ADD_LIST = 'ADD_LIST'
const ADD_CARD = 'ADD_CARD'
const REMOVE_CARD = 'REMOVE_CARD'
const CLONE_CARD = 'CLONE_CARD'
const REORDER_CARDS = 'REORDER_CARDS'

export { 
  ADD_LIST,
  ADD_CARD, REMOVE_CARD, CLONE_CARD, REORDER_CARDS
}
